### ISSUE TITLE
Do you have any documents？

### ISSUE THREAD

**Issue by wynnforthework** [geiszla/CycriptGUI#2]
i want use this project install ipa in windows,when i add `[DllImport(LibiMobileDevice.LIBIMOBILEDEVICE_DLL_PATH, CallingConvention = CallingConvention.Cdecl)]
        static extern InstproxyError instproxy_install(IntPtr instProxyClient,string path, IntPtr clientOptions,IntPtr statusCallBack,IntPtr userData);
        `
it dose't work,i guess is params error, i don't know what the parameters should be,can you help me please.

**Comment by geiszla** [comment]
Unfortunately, this was a very experimental project and didn't get very far. It also hasn't been updated for quite a white, so it may be the case that LibIMobileDevice has changed since, and that's why it doesn't work anymore. In any case, I don't support this project anymore, so I can't answer your message directly, sorry :/
